server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: Nam@135792002
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 395195600772-cn1beq2ta6t2lb2aasn8lhpua4cthoq3.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 847567736882556
            client-secret: f8e0f7034c2219f64b22b070429a9a97
            scope:
              - email
              - public_profile